// SHOPIFY ACTION TYPES
export const FETCH_COLLECTIONS_PENDING = 'FETCH_COLLECTIONS_PENDING';
export const FETCH_COLLECTIONS_REJECTED = 'FETCH_COLLECTIONS_REJECTED';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_REJECTED = 'FETCH_PRODUCTS_REJECTED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING';
export const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_PENDING = 'FETCH_ALL_ORDERS_PENDING';
export const FETCH_ALL_ORDERS_REJECTED = 'FETCH_ALL_ORDERS_REJECTED';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';

// USER ACTION TYPES
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED';
export const FETCHED_USER_SUCCESS = 'FETCHED_USER_SUCCESS';
export const FETCHED_USER_PENDING = 'FETCHED_USER_PENDING';
export const FETCHED_USER_REJECTED = 'FETCHED_USER_REJECTED';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_PENDING = 'LOGOUT_USER_PENDING';
export const LOGOUT_USER_REJECTED = 'LOGOUT_USER_REJECTED';
export const CURRENT_TOUR = 'CURRENT_TOUR';
